version: "3.8"

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=Test
    ports:
      - 5000:3306
  nodeapp:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000